Script started on Fri Mar 16 13:13:27 2018
]0;/home/user
[32muser@v3-572G [33m/home/user[0m
$ whoami; pe[Kwd
user
/home/user
]0;/home/user
[32muser@v3-572G [33m/home/user[0m
$ git ci[Konfig -l
user.email=laura030727@yahoo.com.tw
user.name=laurachenn
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.lab1.url=https://github.com/laurachenn/lab1.git
remote.lab1.fetch=+refs/heads/*:refs/remotes/lab1/*
]0;/home/user
[32muser@v3-572G [33m/home/user[0m
$ git clone https://github/laurachenn/lab1.[K$ git clone https://github/laurachenn/lab1.git
Cloning into 'lab1'...
fatal: unable to access 'https://github/laurachenn/lab1.git/': Could not resolve host: github
]0;/home/user
[32muser@v3-572G [33m/home/user[0m
$ git clone https://github/laurachenn/lab1.git[C./laurachenn/lab1.gitc/laurachenn/lab1.gito/laurachenn/lab1.gitm/laurachenn/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 3, done.[K
remote: Total 3 (delta 0), reused 3 (delta 0), pack-reused 0[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
]0;/home/user
[32muser@v3-572G [33m/home/user[0m
$ exit

Script done on Fri Mar 16 13:15:25 2018
